#**Numpy Exercise**

##Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.



In [ ]:
import numpy as np

In [ ]:
np.array([[2,3,4] , [5,6,7] , [8,9,10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## `Write a NumPy program to reverse an array (the first element becomes the last).`

## `Original array:`

## `[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]`

## `Reverse array:`

## `[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]`

In [ ]:
import numpy as np
arr = np.arange(12,38)
array = arr[:: -1]
print(array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
arr = np.arange(12,38)
reveresed_array = np.flip(arr)
print(reveresed_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## Write a NumPy program to convert an array to a floating type.
##Sample output:

##Original array

##[1, 2, 3, 4] Array converted to a float type:

##[ 1. 2. 3. 4.]

In [ ]:
arr = np.array([1,2,3,4])
float_array = arr.astype(float)
print(float_array)


[1. 2. 3. 4.]


##Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
sum = arr1 + arr2
print(sum)

[ 7  9 11 13 15]


In [ ]:
array1 = np.array([[1,2,3] , [4,5,6]])
array2 = np.array([[7,8,9] , [10,11,12]])

print("array1")
print(array1)

print("\narray2")
print(array2)

result = array1 + array2
print("\nelement wise sum of the 2 numpy arrays is ")
print(result)

array1
[[1 2 3]
 [4 5 6]]

array2
[[ 7  8  9]
 [10 11 12]]

element wise sum of the 2 numpy arrays is 
[[ 8 10 12]
 [14 16 18]]


##From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [34]:
numpy1 = np.array([1, 2, 3, 4, 5])

numpy2 = np.array([6, 2, 8, 4, 10])

matching_indexes = np.where(numpy1 == numpy2)

print("Indexes where elements match:", matching_indexes)

Indexes where elements match: (array([1, 3]),)
